### ISSUE TITLE
DestinationTable Doesn't Support Scrolling

### ISSUE THREAD

**Issue by solbarth** [StanfordCS194/Team-1#38]
If we add too many destinations so that they cannot all be displayed at the same time then the user cannot scroll and see the location names that have been pushed off the table.

**Comment by pjmogan** [comment]
I don't seem to be having this same issue...at least with around 20 destinations, they seem to be all displayed and scrollable

**Comment by zoesol** [comment]
I also found no problem with this. Gonna close the issue for now
